workflows:
  cordova:
    name: Cordova workflow
    environment:
      vars:
        GRADLE_PATH: /Users/builder/programs/gradle-5.6.4/bin
    scripts:
     - npm install
     - sudo npm install -g cordova
     - cordova platform add android
     - echo $GRADLE_PATH
     - export PATH=$GRADLE_PATH:$PATH
     - echo $PATH
     - export PATH=$GRADLE_PATH:$PATH  
     - cordova build android
    artifacts:
     - platforms/android/app/build/outputs/apk/**/*.apk
     - platforms/android/app/build/outputs/apk/**/*.aab
     - $FCI_BUILD_DIR/*.zip
